---
title: "Vorbereitung"
bibliography: "bib/refs.bib"
csl: https://www.zotero.org/styles/apa
engine: knitr
code-annotations: hover
---

Nachdem wir im vorherigen Abschnitt bereits alle Voraussetzungen geschaffen haben (Python installiert, Projektordner und virtuelle Umgebung angelegt, benötigte Pakete installiert), wollen wir hier noch einmal Schritt für Schritt durchgehen, wie wir die Arbeitsumgebung für die Beispiele aus diesem Artikel einrichten können. Die folgenden Schritte müssen nämlich, im Gegensatz zur Installation, jedes Mal durchgeführt werden, wenn wir eine neue Textcodierung beginnen wollen.

## 1 Projektordner öffnen

Den bereits angelegten Projektordner können wir über den Dateimanager (Windows) bzw. Finder (Mac) öffnen. Anschließend navigieren wir zu unserem Projektordner und öffnen darin die Kommandozeile unseres Computers:

::: {.panel-tabset group="os"}

## Linux/Mac

Rechtsklick auf Projektordner im Finder und “Neues Terminal beim Ordner” auswählen

## Windows

Shift + Rechtsklick auf Projektordner im Explorer und “PowerShell-Fenster hier öffnen” auswählen

:::

## 2 Texte vorbereiten

Die Texte, die wir codieren wollen, müssen in einer CSV-Datei im Projektordner vorliegen. Die CSV-Datei muss dabei mindestens eine Spalte mit den zu codierenden Texten enthalten. Optional können weitere Spalten mit Metadaten (z.B. ID, Quelle, Datum) enthalten sein. In den Beispielen aus diesem Artikel liegen die Text in der Spalte `text`. Sollten die Texte in einer anderen Spalte liegen, muss der entsprechende Spaltenname im Code angepasst werden. In den folgenden Beispielen verwenden wir eine Beispieldatei mit dem Namen `example_dataset.csv`, die im Ordner `data` liegt. Diese Beispieldatei enthält zehn Beispieltexte:

:::{.callout-note}
## Code einblenden
Code, der nicht unmittelbar für das Verständnis der Beispiele notwendig ist, wird standardmäßig ausgeblendet. Über den Button "Code" kann der Code bei Bedarf jedoch jederzeit eingeblendet werden.
:::

```{r filename="R"}
#| code-fold: true
readr::read_csv("data/example_dataset.csv", show_col_types = FALSE) #<1>
```

1. Wir lesen die Beispieldatei `example_dataset.csv` ein, die im Ordner `data` liegt. Die Datei enthält zehn Beispieltexte in der Spalte `text`.

## 3 Virtuelle Python-Umgebung aktivieren

Auch wenn wir die virtuelle Python-Umgebung bereits angelegt haben, müssen wir diese jedes Mal aktivieren, wenn wir in der virtuellen Umgebung arbeiten wollen. Hierzu führen wir den folgenden Befehl aus:

:::callout-important
## Achtung
Ist die virtuelle Umgebung bereits aktiviert, darf der folgende Befehl nicht erneut ausgeführt werden, da dies zu Fehlern führen kann. In der Kommandozeile ist die virtuelle Umgebung an einem veränderten Prompt erkennbar, der den Namen der virtuellen Umgebung enthält (z.B. `(env)`). Alternativ können wir in der Konsole den Befehl `echo $VIRTUAL_ENV` (Linux/Mac) bzw. `echo %VIRTUAL_ENV%` (Windows) ausführen. Wenn der Pfad zur virtuellen Umgebung angezeigt wird, ist die virtuelle Umgebung aktiviert. Andernfalls wird eine leere Zeile angezeigt.
:::

::: {.panel-tabset group="os"}

## Linux/Mac

```{.bash filename="Terminal"}
source env/bin/activate #<1>
```

1. Wir aktivieren die virtuelle Python-Umgebung mit dem Namen `env`. Der Name der virtuellen Umgebung kann beliebig gewählt werden, sollte aber idealerweise keine Leer- oder Sonderzeichen enthalten. Er muss außerdem mit dem Namen übereinstimmen, der bei der Anlage der virtuellen Umgebung verwendet wurde.

## Windows

```{.bash filename="Terminal"}
.\env\Scripts\activate #<1>
```

1. Wir aktivieren die virtuelle Python-Umgebung mit dem Namen `env`. Der Name der virtuellen Umgebung kann beliebig gewählt werden, sollte aber idealerweise keine Leer- oder Sonderzeichen enthalten. Er muss außerdem mit dem Namen übereinstimmen, der bei der Anlage der virtuellen Umgebung verwendet wurde.

:::

## 4 Jupyter Notebook öffnen

Mit dem folgenden Befehl können wir schließlich die Jupyter Notebook-Umgebung öffnen, in der wir die Beispiele aus diesem Artikel ausprobieren können. In der Jupyter Notebook-Umgebung können wir dann die Python-Skripte ausführen, die in den folgenden Kapiteln beschrieben werden. 

```{.bash filename="Terminal"}
jupyter notebook #<1>
```

1. Wir öffnen die Jupyter Notebook-Umgebung. Dadurch wird ein neues Fenster in unserem Webbrowser geöffnet, in dem wir die Jupyter Notebook-Umgebung sehen können.

:::callout-tip
## Gut zu wissen

Während die Jupyter Notebook-Umgebung läuft, sollte die Kommandozeile nicht geschlossen werden. Wir sehen in der Kommandozeile währenddessen verschiedene Informationen, z.B. ob die Jupyter Notebook-Umgebung erfolgreich gestartet wurde und unter welcher URL wir die Jupyter Notebook-Umgebung im Browser erreichen können (in der Regel `http://localhost:8888`). Wenn wir die Jupyter Notebook-Umgebung schließen wollen, können wir dies über die Kommandozeile mit `CTRL + C` tun. Anschließend müssen wir die Eingabe mit `y` bestätigen.
:::