project:
  type: website
  lib-dir: site_libs

metadata-files:
  - sections/tutorials/_sidebar.yml
  - sections/paper/_sidebar.yml
  - sections/workshop/_sidebar.yml

lang: en

bibliography: "bib/refs.bib"
csl: "bib/apa.csl"

website:
  title: "Open Source LLMs for Content Analysis"
  site-url: https://llm-content-analysis.com
  navbar:
    right:
      - text: "Tutorials"
        href: sections/tutorials/index.qmd
      - text: "Paper"
        href: sections/paper/index.qmd
      - text: "Workshop"
        href: sections/workshop/index.qmd
  page-footer: "© Dietrich, Possler, & Scheper | [Imprint & Privacy Policy](https://felix-dietrich.de/imprint.html)"

format:
  html:
    toc: true
    page-navigation: true
    number-sections: false
    smooth-scroll: true
    footnotes-hover: true
    code-fold: false
    code-tools: false
    code-line-numbers: false
    highlight-style: gruvbox
    lang: en
    link-external-newwindow: true
    code-annotations: hover
    include-after-body: styles/notebook-embed-offset.html
    theme:
      light: [cosmo, styles/theme.scss]

execute:
  freeze: auto
