project:
  type: website
  lib-dir: site_libs
  
lang: de
language:
  title-block-author-single: "Autor:in"
  title-block-affiliation-single: "Universität"
  title-block-published: ""

bibliography: "bib/refs.bib"
csl: "bib/apa.csl"

website:
  # site-url:
  sidebar:
    style: "floating"
    align: "center"
    logo: "img/transformer.png"
    search: true
    collapse-level: 1
    contents:
      - section: "Anleitungen"
        href: "index.qmd"
        contents:
          - href: "01_installation.qmd"
            text: "Installation"
          - href: "02_setup.qmd"
            text: "Vorbereitung"
          - section: "Textklassifikation"
            contents:
              - href: "03_kategoriespezifisches_Encoder-Modell.qmd"
                text: "Kategoriespezifisches Encoder-Modell"
              - href: "04_aufgabenspezifisches_Encoder-Modell.qmd"
                text: "Aufgabenspezifisches Encoder-Modell"
              - href: "05_universelles_Decoder-Modell.qmd"
                text: "Universelles Decoder-Modell"
      - text: "---"
      - section: "Beispielstudie"
        href: "beispielstudie/00_beispielstudie.qmd"
        contents:
          - href: "beispielstudie/00_goldstandard.qmd"
            text: "Goldstandard"
          - href: "beispielstudie/01_kategoriespezifisches_Encoder-Modell.qmd"
            text: "Kategoriespezifisches Encoder-Modell"
          - href: "beispielstudie/02_aufgabenspezifisches_Encoder-Modell.qmd"
            text: "Aufgabenspezifisches Encoder-Modell"
          - href: "beispielstudie/03_universelles_Decoder-Modell.qmd"
            text: "Universelles Decoder-Modell"
          - href: "beispielstudie/04_manuelle_Inhaltsanalyse.qmd"
            text: "Manuelle Inhaltsanalyse"
          - href: "beispielstudie/05_dictionary.qmd"
            text: "Off-the-shelf Diktionär"
          - href: "beispielstudie/06_machine_learning.qmd"
            text: "Überwachtes maschinelles Lernen"
          - href: "beispielstudie/07_validierung.qmd"
            text: "Validierung"

format:
  html:
    toc: true
    page-navigation: true
    number-sections: false
    smooth-scroll: true
    footnotes-hover: true
    code-fold: false
    code-tools: false
    code-line-numbers: false
    highlight-style: gruvbox
    lang: de-DE
    link-external-newwindow: true
    code-annotations: hover
theme:
  light: [cosmo, theme.scss]
  
execute:
  freeze: auto