---
title: "Aufgabenspezifisches Encoder-Modell"
subtitle: "Beispielstudie"
engine: knitr
---

## Die Methode

Als aufgabenspezifisches Encoder-Modell wurde das Off-the-Shelf-Modell *bge-m3-zeroshot-v2.0* von @laurerBuildingEfficientUniversal2024 verwendet, das für die NLI-Aufgabe ausgelegt ist (zur NLI-Aufgabe s. Abschn. 2.1 im Paper). Das Modell bot sich an, da es im Hinblick auf die AIA von Texten durch Kommunikationswissenschaftler\*innen entwickelt und ausführlich evaluiert worden ist [@laurerBuildingEfficientUniversal2024]. Es basiert auf dem multilingualen Encoder-Modell BGE-M3 [@chenBGEM3EmbeddingMultilingual2024] und wurde mit einer Mischung aus fünf NLI-Datensätzen und 28 weiteren Klassifikationsdatensätzen trainiert. Die Trainingsdatensätze des Modells decken dabei Aufgaben wie Sentimentanalyse und Emotionsklassifikation ab. Die drei möglichen Ausprägungen der Tonalität wurden jeweils als zu prüfende Hypothese formuliert ("Die Stimmung beziehungsweise Tonalität des Textes ist {positiv, neutral, negativ}"). Das Modell ermittelte je Ausprägung einen Wahrscheinlichkeitswert und die wahrscheinlichste Ausprägung wurde hier als Codierentscheidung des Modells betrachtet.

## Klassifikation

```{python filename="Python"}
#| eval: false

import pandas as pd                                                              # <1>
from transformers import pipeline                                                # <1>

daten = pd.read_csv("sections/paper/beispielstudie/data/00_goldstandard.csv")                   # <2>
datenliste = list(daten["text"])                                                 # <2>

template = "Die Stimmung beziehungsweise Tonalität des Textes ist {}"            # <3>
labels = ["positiv", "neutral", "negativ"]                                       # <3>

zeroshot_classifier = pipeline("zero-shot-classification",                       # <4>
                                model = "MoritzLaurer/bge-m3-zeroshot-v2.0")     # <4>

results = zeroshot_classifier(datenliste, candidate_labels=labels,               # <5>
                              hypothesis_template=template, multi_label=False)   # <5>

labels = set(label for item in results for label in item['labels'])              # <6>
out_dict = {label: [] for label in labels}                                       # <6>
out_dict['sequence'] = []                                                        # <6>

for item in results:                                                             # <6>
    out_dict['sequence'].append(item['sequence'])                                # <6>
    for label in labels:                                                         # <6>
        if label in item['labels']:                                              # <6>
            out_dict[label].append(item['scores'][item['labels'].index(label)])  # <6>
        else:                                                                    # <6>
            out_dict[label].append(None)                                         # <6>

vergleich = pd.DataFrame(out_dict).drop("sequence", axis=1).join(daten)         # <7>
vergleich.to_csv("sections/paper/beispielstudie/data/02_aufgabenspezifisches_Encoder-Modell.csv", index=False) # <7>

```

1. Import der notwendigen Bibliotheken.
2. Laden der Daten.
3. Definition der Hypothesen-Vorlage und der möglichen Labels.
4. Initialisierung des Zero-Shot-Klassifikations-Pipelines mit dem spezifischen Modell.
5. Durchführung der Klassifikation.
6. Extrahieren der Labels aus den Ergebnissen.
7. Zusammenführen der Ergebnisse mit den Originaldaten und Speichern in einer CSV-Datei.

## Ergebnisse

Schauen wir uns eine kleine Auswahl der Ergebnisse an. Wir setzen einen Seed, um die gleiche Auswahl an Texten zu bekommen wie bei den anderen Modellen.

```{r filename="R"}
#| code-fold: true
set.seed(42)
readr::read_csv(here::here("sections/paper/beispielstudie/data/02_aufgabenspezifisches_Encoder-Modell.csv"), show_col_types = FALSE) |>
  dplyr::arrange(desc(id)) |>
  dplyr::select(positiv, neutral, negativ, sentiment_gs, textart, text) |>
  dplyr::sample_n(5)
```
