---
title: "Beispielstudie"
subtitle: "Sentiment-Analyse als Beispiel"
---

Als Ergänzung zum schematischen Überblick (s. [Anleitung](../index.qmd) und Abschn. 4 im Paper) demonstrieren wir nun den Einsatz LLM-basierter Verfahren via Hugging Face für die AIA anhand einer empirischen Beispielstudie. Als Anwendungsfall dient die Sentiment-Analyse (d. h., die Codierung der Tonalität von Texten), eine zentrale Variante kommunikationswissenschaftlicher Inhaltsanalysen, besonders im automatisierten Bereich [vgl. @kesslerManuelleStandardisierteInhaltsanalyse2023, S. 18]. Im Vergleich zu komplexeren Konstrukten wie Inzivilität [vgl. @esauContentAnalysisResearch2023, S. 455–457] ist Tonalität zudem leicht verständlich und eignet sich daher gut als Demonstrationsfall.

Die Beispielstudie soll drei Beiträge leisten: Erstens stellt der praxisnahe und ausführlich kommentierte Code zur Beispielstudie auf dieser Begleitwebsite eine gute Grundlage für die Übertragung der Verfahren auf eigene Zwecke dar. Zweitens erfordert der Einsatz von off-the-shelf Ressourcen für die AIA stets eine Validierung [vgl. @grimmerTextDataPromise2013, S. 271], das trifft auch auf LLM-basierte Verfahren zu [vgl. @weberEvaluationAllYou2023]. Die Beispielstudie demonstriert eine solche Validierung durch den Vergleich der Codierung von drei LLM-basierten Verfahren – einem kategorie- und einem aufgabenspezifischen Encoder-Modell sowie einem universellen Decoder-Modell – mit einem Goldstandard, d. h., einem von Expert\*innen manuell codierten Datensatz mit hoher Validität und Reliabilität. Drittens vergleichen wir die Leistung der drei LLM-basierten Verfahren mit einer typischen manuellen Inhaltsanalyse sowie den populärsten AIA-Verfahren im Fach: der Analyse mittels Diktionär und klassischer überwachter Lernalgorithmen [vgl. @haseComputationalTurnInterdisciplinary2023; @omniaScopingReviewComputational2023]. Die Beispielstudie liefert damit Hinweise zur Leistungsfähigkeit gebrauchsfertiger LLMs im Vergleich zu etablierten Verfahren, ohne jedoch den Anspruch einer großangelegten Evaluation zu erheben [vgl. für solche Evaluationsstudien @laurerLessAnnotatingMore2024; @rathjeGPTEffectiveTool2024; @viehmannInvestigatingOpinionsPublic2023; @widmannCreatingComparingDictionary2023].

Als Datengrundlage für die Beispielstudie diente das Untersuchungsmaterial einer Inhaltsanalyse von @spatzeneggerSocialMediaAls2020, das insgesamt 3.054 deutschsprachige Beiträge in drei verschiedenen Textsorten umfasst: Tageszeitungsartikel (*n* = 862), Facebook-Posts (*n* = 1.156) und Tweets (*n* = 1.036). Die Beiträge wurden in Deutschland, Österreich und der Schweiz zwischen dem 09.03.2019 und 31.05.2019 veröffentlicht. Die Online- als auch Offline-Zeitungsartikel stammen von jeweils einer Qualitäts- und Boulevardzeitung pro Land; die Social-Media-Beiträge von drei Politiker*innen pro Land. @spatzeneggerSocialMediaAls2020 hat in ihrer Studie das gesamte Material manuell codiert, unter anderem hinsichtlich der Tonalität der Beiträge. Die Weiterverwendung dieser Daten war forschungsökonomisch sinnvoll und ermöglichte es uns zudem, auf die manuelle Codierung von @spatzeneggerSocialMediaAls2020 zurückzugreifen (z. B. für das Training der maschinellen Lernverfahren).